source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CurrencyTextField_Example', :exclusive => true do
  pod "CurrencyTextField", :path => "../"
end

target 'CurrencyTextField_Tests', :exclusive => true do
  pod "CurrencyTextField", :path => "../"

  
end
